proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=video_cache:10m
                 max_size=1g inactive=60m use_temp_path=off;

upstream s3_origin {
    server segments-bucket:80;
}

server {
    listen 8080;
    server_name _; 

    include /etc/nginx/conf.d/headers.conf;
    include /etc/nginx/conf.d/cache.conf;

    location /hls/ {
        proxy_pass http://s3_origin;
        proxy_cache video_cache;
        proxy_cache_valid 200 1h;
    }

    location = /health {
        access_log off;
        add_header Content-Type application/json;
        return 200 '{"status":"ok"}';
    }
}
